#配置端口
server:
  port: 9090
#  servlet:
#    context-path: /pipe

### thymeleaf模板配置
spring:
#  thymeleaf:
#    #热部署文件，页面不产生缓存，及时更新
#    cache: false
#    prefix: classpath:/templates/
#    suffix: .html
#    mode: HTML5
#    encoding: utf-8
  servlet:
    content-type: text/html
    ## 设置上传文件大小
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
